language: node_js
node_js:
  - "0.10"
notifications:
  email: false
before_script:
  - "npm install -g bower testem grunt-cli"
  - "bower install"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 5"
script:
  - "grunt jshint"
  - "grunt requirejs"
  - "testem ci --launch Firefox"
  - "node ./test/coverage/server.js"
  - "cd test"
  - "cat coverage/result.lcov | ../node_modules/coveralls/bin/coveralls.js"
